#!/bin/bash

echo "🚀 Brandon Drake Digital CV - Deployment Instructions"
echo "=================================================="
echo ""
echo "Your digital CV is ready for deployment to GitHub Pages!"
echo ""
echo "📋 NEXT STEPS:"
echo ""
echo "1. Create a GitHub repository:"
echo "   - Go to https://github.com/new"
echo "   - Repository name: brandon-drake-cv"
echo "   - Make it public"
echo "   - Don't initialize with README (we have files already)"
echo ""
echo "2. Update the homepage URL in package.json:"
echo "   Replace 'brandon-drake' with your GitHub username"
echo ""
echo "3. Push to GitHub:"
echo "   git remote add origin https://github.com/YOUR-USERNAME/brandon-drake-cv.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "4. Enable GitHub Pages:"
echo "   - Go to repository Settings > Pages"
echo "   - Source: GitHub Actions"
echo ""
echo "🔧 MANUAL DEPLOYMENT (Alternative):"
echo "   yarn deploy"
echo ""
echo "📱 LOCAL DEVELOPMENT:"
echo "   yarn start     # Start development server"
echo "   yarn build     # Build for production"
echo ""
echo "🌐 Your CV will be live at:"
echo "   https://YOUR-USERNAME.github.io/brandon-drake-cv"
echo ""
echo "📚 For detailed instructions, see DEPLOYMENT.md"
echo ""
